"""Configuration loading and project initialization."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

from abqbatch.exceptions import ConfigError

DEFAULT_PROJECT_YML = """project:
  name: basic_project

abaqus:
  command: abaqus
  cpus: 8
  memory: 90%
  scratch: work/scratch
  interactive: true

runner:
  max_parallel: 1
  timeout_seconds: null
  stop_on_failure: false
  continue_after_failure: true
  retry_failed: false

paths:
  raw_inp: raw_inp
  work: work
  reports: reports
  database: db/state.sqlite

generation:
  patch_mode: anchor_then_block
  add_restart_write: true
  add_standard_output: true
"""

DEFAULT_MATERIALS_YML = """materials:
  steel_E210GPa:
    model: elastic
    name: Steel
    density: 7.85e-9
    elastic:
      E: 210000.0
      nu: 0.30

  steel_plastic_A:
    model: elastic_plastic
    name: Steel
    density: 7.85e-9
    elastic:
      E: 210000.0
      nu: 0.30
    plastic:
      - [250.0, 0.0000]
      - [300.0, 0.0100]
      - [350.0, 0.0300]
"""

DEFAULT_LOADS_YML = """loads:
  disp_ramp_y:
    type: displacement_control
    step: Step-1
    target_set: RP_LOAD
    dof: 2
    value: -1.0
    amplitude:
      name: Amp-Ramp
      data:
        - [0.0, 0.0]
        - [1.0, 1.0]

  force_ramp_y:
    type: force_control
    step: Step-1
    target_set: RP_LOAD
    dof: 2
    value: -1000.0
    amplitude:
      name: Amp-Ramp
      data:
        - [0.0, 0.0]
        - [1.0, 1.0]

  pressure_ramp:
    type: pressure
    step: Step-1
    surface: SURF_LOAD
    value: 5.0
    amplitude:
      name: Amp-Ramp
      data:
        - [0.0, 0.0]
        - [1.0, 1.0]
"""

DEFAULT_POSTPROCESS_YML = """profiles:
  default:
    history:
      - name: rf_u_curve
        step: Step-1
        region: Node ASSEMBLY.RP_LOAD
        x: U2
        y: RF2
        output: history_curves.csv

    field:
      - name: max_mises
        step: Step-1
        frame: last
        instance: PART-1-1
        element_set: ALL_ELEMENTS
        variable: S
        invariant: Mises
        reduction: max

      - name: max_peeq
        step: Step-1
        frame: last
        instance: PART-1-1
        element_set: ALL_ELEMENTS
        variable: PEEQ
        reduction: max
"""


@dataclass(frozen=True)
class ProjectConfig:
    """Resolved project paths and raw configuration dictionaries."""

    root: Path
    project: dict[str, Any]
    materials: dict[str, Any]
    loads: dict[str, Any]
    postprocess: dict[str, Any]

    @property
    def raw_inp_dir(self) -> Path:
        return self.root / self.project["paths"]["raw_inp"]

    @property
    def work_dir(self) -> Path:
        return self.root / self.project["paths"]["work"]

    @property
    def reports_dir(self) -> Path:
        return self.root / self.project["paths"]["reports"]

    @property
    def db_path(self) -> Path:
        return self.root / self.project["paths"]["database"]


def read_yaml(path: Path) -> dict[str, Any]:
    """Read a YAML mapping from disk."""

    if not path.exists():
        raise ConfigError(f"Missing configuration file: {path}")
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ConfigError(f"Configuration must be a mapping: {path}")
    return data


def write_yaml(path: Path, data: dict[str, Any]) -> None:
    """Write a YAML mapping with stable key order."""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


def load_project(project_root: Path) -> ProjectConfig:
    """Load all project-level YAML configuration files."""

    root = project_root.resolve()
    configs = root / "configs"
    project = yaml.safe_load(DEFAULT_PROJECT_YML) or {}
    project.update(read_yaml(configs / "project.yml"))
    materials = read_yaml(configs / "materials.yml")
    loads = read_yaml(configs / "load_schemes.yml")
    postprocess = read_yaml(configs / "postprocess.yml")
    return ProjectConfig(root, project, materials, loads, postprocess)


def project_relative(path: Path, root: Path) -> str:
    """Return a POSIX-style path relative to the project root when possible."""

    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return path.as_posix()



def _default_inp_text(model_name: str, length: float) -> str:
    return f"""*Heading
{model_name} generated by abqbatch init
*Part, name=PART-1
*Node
1, 0., 0., 0.
2, {length}, 0., 0.
3, {length}, 1., 0.
4, 0., 1., 0.
5, 0., 0., 1.
6, {length}, 0., 1.
7, {length}, 1., 1.
8, 0., 1., 1.
*Element, type=C3D8
1, 1,2,3,4,5,6,7,8
*Nset, nset=FIXED
1, 4, 5, 8
*Nset, nset=RP_LOAD
2, 3, 6, 7
*Elset, elset=ALL_ELEMENTS
1
*Solid Section, elset=ALL_ELEMENTS, material=Steel
,
*Material, name=Steel
*Density
7.85e-9
*Elastic
210000., 0.30
*End Part
*Assembly, name=ASSEMBLY
*Instance, name=PART-1-1, part=PART-1
*End Instance
*Nset, nset=RP_LOAD, instance=PART-1-1
2, 3, 6, 7
*End Assembly
*Step, name=Step-1
*Static
0.1, 1.0
*Boundary
FIXED, 1, 3, 0.
*Cload
RP_LOAD, 2, -1.
*Output, field
*Node Output
U, RF
*Element Output
S, E
*End Step
"""


def _write_default_raw_inputs(root: Path) -> list[Path]:
    raw_dir = root / "raw_inp"
    if any(raw_dir.glob("*.inp")):
        return []
    files = {
        raw_dir / "model_001.inp": _default_inp_text("model_001", 1.0),
        raw_dir / "model_002.inp": _default_inp_text("model_002", 2.0),
    }
    for file_path, content in files.items():
        file_path.write_text(content, encoding="utf-8")
    return list(files)
def init_project(path: Path, force: bool = False) -> list[Path]:
    """Create a new abqbatch project layout and default YAML files."""

    root = path.resolve()
    created: list[Path] = []
    for dirname in ("configs", "raw_inp", "work", "reports", "db", "logs"):
        target = root / dirname
        target.mkdir(parents=True, exist_ok=True)
        created.append(target)

    defaults = {
        root / "configs" / "project.yml": DEFAULT_PROJECT_YML,
        root / "configs" / "materials.yml": DEFAULT_MATERIALS_YML,
        root / "configs" / "load_schemes.yml": DEFAULT_LOADS_YML,
        root / "configs" / "postprocess.yml": DEFAULT_POSTPROCESS_YML,
    }
    for file_path, content in defaults.items():
        if force or not file_path.exists():
            file_path.write_text(content, encoding="utf-8")
            created.append(file_path)
    created.extend(_write_default_raw_inputs(root))
    return created
