"""Generate isolated case work directories and derived Abaqus input decks."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from shutil import copyfile
from typing import Any

import yaml

from abqbatch import db
from abqbatch.config import ProjectConfig, project_relative
from abqbatch.exceptions import Status
from abqbatch.hashes import sha256_file
from abqbatch.inp_parser import InpDeck
from abqbatch.inventory import read_cases_csv
from abqbatch.patchers import (
    OUTPUT_INC,
    RESTART_INC,
    ensure_output,
    ensure_restart,
    generate_load_block,
    generate_material_block,
    patch_load,
    patch_material,
)


@dataclass(frozen=True)
class GeneratedCase:
    case_id: str
    case_dir: Path
    generated_inp: Path
    generated_sha256: str


def _profile(container: dict[str, Any], section: str, name: str) -> dict[str, Any]:
    try:
        return container[section][name]
    except KeyError as exc:
        raise KeyError(f"Unknown {section} profile: {name}") from exc


def generate_case(config: ProjectConfig, case_row: dict[str, Any]) -> GeneratedCase:
    """Generate all input artifacts for one case."""

    case_id = case_row["case_id"]
    source_path = config.root / case_row["source_inp"]
    source_sha = sha256_file(source_path)
    material_profile_name = case_row["material_profile"]
    load_profile_name = case_row["load_profile"]
    material_profile = _profile(config.materials, "materials", material_profile_name)
    load_profile = _profile(config.loads, "loads", load_profile_name)

    case_dir = config.work_dir / "cases" / case_id
    input_dir = case_dir / "input"
    input_dir.mkdir(parents=True, exist_ok=True)

    original = input_dir / "original.inp"
    generated = input_dir / "generated.inp"
    material_inc = input_dir / "material.inc"
    load_inc = input_dir / "load.inc"
    restart_inc = input_dir / "restart.inc"
    output_inc = input_dir / "output.inc"

    copyfile(source_path, original)
    material_inc.write_text(generate_material_block(material_profile), encoding="utf-8")
    load_inc.write_text(generate_load_block(load_profile), encoding="utf-8")
    restart_inc.write_text(RESTART_INC, encoding="utf-8")
    output_inc.write_text(OUTPUT_INC, encoding="utf-8")

    deck = InpDeck.from_file(original)
    patch_material(deck, material_profile["name"], "*Include, input=material.inc\n")
    patch_load(deck, load_profile["step"], "*Include, input=load.inc\n")
    generation = config.project.get("generation") or {}
    if generation.get("add_restart_write", True):
        ensure_restart(deck, load_profile["step"])
    if generation.get("add_standard_output", True):
        ensure_output(deck, load_profile["step"])

    header = [
        "** Generated by abqbatch",
        f"** case_id = {case_id}",
        f"** source_sha256 = {source_sha}",
        f"** material_profile = {material_profile_name}",
        f"** load_profile = {load_profile_name}",
    ]
    generated.write_text("\n".join(header) + "\n" + deck.to_text(), encoding="utf-8")

    artifacts = {
        "original_inp": original,
        "generated_inp": generated,
        "material_inc": material_inc,
        "load_inc": load_inc,
        "restart_inc": restart_inc,
        "output_inc": output_inc,
    }
    meta = {
        "case_id": case_id,
        "source_inp": case_row["source_inp"],
        "source_sha256": source_sha,
        "material_profile": material_profile_name,
        "load_profile": load_profile_name,
        "post_profile": case_row.get("post_profile", "default"),
        "artifacts": {
            name: {
                "path": project_relative(path, config.root),
                "sha256": sha256_file(path),
            }
            for name, path in artifacts.items()
        },
    }
    (case_dir / "meta.yml").write_text(yaml.safe_dump(meta, sort_keys=False), encoding="utf-8")

    generated_sha = sha256_file(generated)
    db.upsert_case(
        config.db_path,
        {
            "case_id": case_id,
            "source_inp": case_row["source_inp"],
            "source_sha256": source_sha,
            "generated_inp": project_relative(generated, config.root),
            "generated_sha256": generated_sha,
            "material_profile": material_profile_name,
            "load_profile": load_profile_name,
            "post_profile": case_row.get("post_profile", "default"),
            "job_name": case_id,
            "status": Status.GENERATED.value,
            "priority": int(case_row.get("priority") or 100),
        },
    )
    for kind, artifact in artifacts.items():
        db.add_artifact(config.db_path, case_id, None, kind, artifact, sha256_file(artifact))
    db.add_artifact(
        config.db_path,
        case_id,
        None,
        "meta",
        case_dir / "meta.yml",
        sha256_file(case_dir / "meta.yml"),
    )
    return GeneratedCase(case_id, case_dir, generated, generated_sha)


def generate_project(config: ProjectConfig) -> list[GeneratedCase]:
    """Generate all cases listed in configs/cases.csv."""

    db.init_db(config.db_path)
    rows = read_cases_csv(config.root / "configs" / "cases.csv")
    return [generate_case(config, row) for row in rows]
