profiles:
  default:
    history:
      - name: rf_u_curve
        step: Step-1
        region: Node ASSEMBLY.RP_LOAD
        x: U2
        y: RF2
        output: history_curves.csv

    field:
      - name: max_mises
        step: Step-1
        frame: last
        instance: PART-1-1
        element_set: ALL_ELEMENTS
        variable: S
        invariant: Mises
        reduction: max

      - name: max_peeq
        step: Step-1
        frame: last
        instance: PART-1-1
        element_set: ALL_ELEMENTS
        variable: PEEQ
        reduction: max
